//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSOAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://redes", ConfigurationName="ServiceReference1.funciones")]
    public interface funciones
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://redes no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WsSOAP.validarNombreResponse validarNombre(WsSOAP.validarNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSOAP.validarNombreResponse> validarNombreAsync(WsSOAP.validarNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://redes no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WsSOAP.separarNombreResponse separarNombre(WsSOAP.separarNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSOAP.separarNombreResponse> separarNombreAsync(WsSOAP.separarNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Rut del espacio de nombres http://redes no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WsSOAP.digitoVerificadorResponse digitoVerificador(WsSOAP.digitoVerificadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSOAP.digitoVerificadorResponse> digitoVerificadorAsync(WsSOAP.digitoVerificadorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Rut del espacio de nombres http://redes no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WsSOAP.verificadorRutResponse verificadorRut(WsSOAP.verificadorRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSOAP.verificadorRutResponse> verificadorRutAsync(WsSOAP.verificadorRutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNombreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNombre", Namespace="http://redes", Order=0)]
        public WsSOAP.validarNombreRequestBody Body;
        
        public validarNombreRequest()
        {
        }
        
        public validarNombreRequest(WsSOAP.validarNombreRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class validarNombreRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        public validarNombreRequestBody()
        {
        }
        
        public validarNombreRequestBody(string Nombre)
        {
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNombreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNombreResponse", Namespace="http://redes", Order=0)]
        public WsSOAP.validarNombreResponseBody Body;
        
        public validarNombreResponse()
        {
        }
        
        public validarNombreResponse(WsSOAP.validarNombreResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class validarNombreResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool validarNombreReturn;
        
        public validarNombreResponseBody()
        {
        }
        
        public validarNombreResponseBody(bool validarNombreReturn)
        {
            this.validarNombreReturn = validarNombreReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class separarNombreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="separarNombre", Namespace="http://redes", Order=0)]
        public WsSOAP.separarNombreRequestBody Body;
        
        public separarNombreRequest()
        {
        }
        
        public separarNombreRequest(WsSOAP.separarNombreRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class separarNombreRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        public separarNombreRequestBody()
        {
        }
        
        public separarNombreRequestBody(string Nombre)
        {
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class separarNombreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="separarNombreResponse", Namespace="http://redes", Order=0)]
        public WsSOAP.separarNombreResponseBody Body;
        
        public separarNombreResponse()
        {
        }
        
        public separarNombreResponse(WsSOAP.separarNombreResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class separarNombreResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string separarNombreReturn;
        
        public separarNombreResponseBody()
        {
        }
        
        public separarNombreResponseBody(string separarNombreReturn)
        {
            this.separarNombreReturn = separarNombreReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class digitoVerificadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="digitoVerificador", Namespace="http://redes", Order=0)]
        public WsSOAP.digitoVerificadorRequestBody Body;
        
        public digitoVerificadorRequest()
        {
        }
        
        public digitoVerificadorRequest(WsSOAP.digitoVerificadorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class digitoVerificadorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Rut;
        
        public digitoVerificadorRequestBody()
        {
        }
        
        public digitoVerificadorRequestBody(string Rut)
        {
            this.Rut = Rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class digitoVerificadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="digitoVerificadorResponse", Namespace="http://redes", Order=0)]
        public WsSOAP.digitoVerificadorResponseBody Body;
        
        public digitoVerificadorResponse()
        {
        }
        
        public digitoVerificadorResponse(WsSOAP.digitoVerificadorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class digitoVerificadorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string digitoVerificadorReturn;
        
        public digitoVerificadorResponseBody()
        {
        }
        
        public digitoVerificadorResponseBody(string digitoVerificadorReturn)
        {
            this.digitoVerificadorReturn = digitoVerificadorReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificadorRutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificadorRut", Namespace="http://redes", Order=0)]
        public WsSOAP.verificadorRutRequestBody Body;
        
        public verificadorRutRequest()
        {
        }
        
        public verificadorRutRequest(WsSOAP.verificadorRutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class verificadorRutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Rut;
        
        public verificadorRutRequestBody()
        {
        }
        
        public verificadorRutRequestBody(string Rut)
        {
            this.Rut = Rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificadorRutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificadorRutResponse", Namespace="http://redes", Order=0)]
        public WsSOAP.verificadorRutResponseBody Body;
        
        public verificadorRutResponse()
        {
        }
        
        public verificadorRutResponse(WsSOAP.verificadorRutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://redes")]
    public partial class verificadorRutResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verificadorRutReturn;
        
        public verificadorRutResponseBody()
        {
        }
        
        public verificadorRutResponseBody(string verificadorRutReturn)
        {
            this.verificadorRutReturn = verificadorRutReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface funcionesChannel : WsSOAP.funciones, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class funcionesClient : System.ServiceModel.ClientBase<WsSOAP.funciones>, WsSOAP.funciones
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public funcionesClient() : 
                base(funcionesClient.GetDefaultBinding(), funcionesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.funciones.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public funcionesClient(EndpointConfiguration endpointConfiguration) : 
                base(funcionesClient.GetBindingForEndpoint(endpointConfiguration), funcionesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public funcionesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(funcionesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public funcionesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(funcionesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public funcionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsSOAP.validarNombreResponse WsSOAP.funciones.validarNombre(WsSOAP.validarNombreRequest request)
        {
            return base.Channel.validarNombre(request);
        }
        
        public bool validarNombre(string Nombre)
        {
            WsSOAP.validarNombreRequest inValue = new WsSOAP.validarNombreRequest();
            inValue.Body = new WsSOAP.validarNombreRequestBody();
            inValue.Body.Nombre = Nombre;
            WsSOAP.validarNombreResponse retVal = ((WsSOAP.funciones)(this)).validarNombre(inValue);
            return retVal.Body.validarNombreReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsSOAP.validarNombreResponse> WsSOAP.funciones.validarNombreAsync(WsSOAP.validarNombreRequest request)
        {
            return base.Channel.validarNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsSOAP.validarNombreResponse> validarNombreAsync(string Nombre)
        {
            WsSOAP.validarNombreRequest inValue = new WsSOAP.validarNombreRequest();
            inValue.Body = new WsSOAP.validarNombreRequestBody();
            inValue.Body.Nombre = Nombre;
            return ((WsSOAP.funciones)(this)).validarNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsSOAP.separarNombreResponse WsSOAP.funciones.separarNombre(WsSOAP.separarNombreRequest request)
        {
            return base.Channel.separarNombre(request);
        }
        
        public string separarNombre(string Nombre)
        {
            WsSOAP.separarNombreRequest inValue = new WsSOAP.separarNombreRequest();
            inValue.Body = new WsSOAP.separarNombreRequestBody();
            inValue.Body.Nombre = Nombre;
            WsSOAP.separarNombreResponse retVal = ((WsSOAP.funciones)(this)).separarNombre(inValue);
            return retVal.Body.separarNombreReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsSOAP.separarNombreResponse> WsSOAP.funciones.separarNombreAsync(WsSOAP.separarNombreRequest request)
        {
            return base.Channel.separarNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsSOAP.separarNombreResponse> separarNombreAsync(string Nombre)
        {
            WsSOAP.separarNombreRequest inValue = new WsSOAP.separarNombreRequest();
            inValue.Body = new WsSOAP.separarNombreRequestBody();
            inValue.Body.Nombre = Nombre;
            return ((WsSOAP.funciones)(this)).separarNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsSOAP.digitoVerificadorResponse WsSOAP.funciones.digitoVerificador(WsSOAP.digitoVerificadorRequest request)
        {
            return base.Channel.digitoVerificador(request);
        }
        
        public string digitoVerificador(string Rut)
        {
            WsSOAP.digitoVerificadorRequest inValue = new WsSOAP.digitoVerificadorRequest();
            inValue.Body = new WsSOAP.digitoVerificadorRequestBody();
            inValue.Body.Rut = Rut;
            WsSOAP.digitoVerificadorResponse retVal = ((WsSOAP.funciones)(this)).digitoVerificador(inValue);
            return retVal.Body.digitoVerificadorReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsSOAP.digitoVerificadorResponse> WsSOAP.funciones.digitoVerificadorAsync(WsSOAP.digitoVerificadorRequest request)
        {
            return base.Channel.digitoVerificadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsSOAP.digitoVerificadorResponse> digitoVerificadorAsync(string Rut)
        {
            WsSOAP.digitoVerificadorRequest inValue = new WsSOAP.digitoVerificadorRequest();
            inValue.Body = new WsSOAP.digitoVerificadorRequestBody();
            inValue.Body.Rut = Rut;
            return ((WsSOAP.funciones)(this)).digitoVerificadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsSOAP.verificadorRutResponse WsSOAP.funciones.verificadorRut(WsSOAP.verificadorRutRequest request)
        {
            return base.Channel.verificadorRut(request);
        }
        
        public string verificadorRut(string Rut)
        {
            WsSOAP.verificadorRutRequest inValue = new WsSOAP.verificadorRutRequest();
            inValue.Body = new WsSOAP.verificadorRutRequestBody();
            inValue.Body.Rut = Rut;
            WsSOAP.verificadorRutResponse retVal = ((WsSOAP.funciones)(this)).verificadorRut(inValue);
            return retVal.Body.verificadorRutReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsSOAP.verificadorRutResponse> WsSOAP.funciones.verificadorRutAsync(WsSOAP.verificadorRutRequest request)
        {
            return base.Channel.verificadorRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsSOAP.verificadorRutResponse> verificadorRutAsync(string Rut)
        {
            WsSOAP.verificadorRutRequest inValue = new WsSOAP.verificadorRutRequest();
            inValue.Body = new WsSOAP.verificadorRutRequestBody();
            inValue.Body.Rut = Rut;
            return ((WsSOAP.funciones)(this)).verificadorRutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.funciones))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.funciones))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/WebServiceProject/services/funciones");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return funcionesClient.GetBindingForEndpoint(EndpointConfiguration.funciones);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return funcionesClient.GetEndpointAddress(EndpointConfiguration.funciones);
        }
        
        public enum EndpointConfiguration
        {
            
            funciones,
        }
    }
}
